config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :cities
  resources :orders
  resources :customers
  resources :suppliers
  # resources :sessions, only: [:create, :destroy]

  root  'customers#index'
  match '/login', to: 'sessions#new', via: 'get'
  match '/login', to: 'sessions#create', via: 'post'
  match '/logout', to: 'sessions#destroy', via: 'delete'

  match '/signup', to: 'customers#new', via: 'get'
  match '/signup', to: 'customers#create', via: 'post'

  match '/customers', to: 'customers#index', via: 'get'
  match '/customer', to: 'customers#show', via: 'get'
  match '/customers', to: 'customers#destroy', via: 'delete'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  VALID_PHONE_NUMBER = /0[569][035-9](\d){7}/
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  ROLES = [:guest, :custom]

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, format: { with: VALID_PHONE_NUMBER }, uniqueness: true
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}
  has_secure_password
  validates :city_id, presence: true
  validates :role, presence: true, inclusion: {in: ['guest', 'customer']}

  has_many :orders
  belongs_to :city

  attr_accessor :remember_token

  class << self
    def digest (string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
          BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = Customer.new_token
    update_attribute(:remember_digest, Customer.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # def is?(requested_role)
  #   self.role == requested_role.to_s
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # before_action :set_customer, only: [:show, :edit, :update, :destroy]

  before_action :logged_in_customer, only: [:show, :edit, :update, :destroy]
  before_action :correct_customer, only: [:edit, :update]

  def index
    @customers = Customer.all
  end

  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  def create
    @customer = Customer.new(customer_params)
    @customer.role = :customer

      if @customer.save
        log_in(@customer)
        redirect_to @customer
      else
        format.html { render :new }
      end
  end

  # PATCH/PUT /customers/1
  def update
    @customer = Customer.find(params[:id])

      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
      else
        format.html { render :edit }
      end
  end

  # DELETE /customers/1
  def destroy
    Customer.find(params[:id]).destroy
      redirect_to customers_path
  end

  private
    def set_customer
      @customer = Customer.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :phone, :email, :password, :city_id)
    end

    def logged_in_customer
      unless logged_in?
        store_location
        redirect_to login_url
      end
    end

    def correct_customer
      @customer = Customer.find(params[:id])
      redirect_to(orders_path) unless @customer.current_customer?(@customer)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
  include SessionsHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer, url: yield(:path)) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br>
    <%= f.password_field :password_confirmation %>
    </div>
    <div class="field">
      <%= f.select :city_id, options_for_select(City.all.map {|city| [city.name, city.id]}) %><br>
    </div>
  <div class="actions">
    <%= f.submit yield(:button_text)%>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<% provide(:path, "/customers/#{current_customer.id}") %>
<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<!--<p id="notice">%= notice %></p>-->

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.phone %></td>
        <!--<td>%= link_to 'Show', customer %></td>-->
        <!--<td>%= link_to 'Edit', edit_customer_path(customer) %></td>-->
        <!--<td>%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if !logged_in? %>
  <%= link_to 'Log in', login_path %><br>
  <%= link_to 'New Customer', new_customer_path %><br>
<% else %>
  <%= link_to 'Log out', logout_path, method: :delete %>
<% end %>

app/views/customers/new.html.erb
<h1>Registration</h1>

<% provide(:button_text, 'Sign up') %>
<% provide(:path, signup_path) %>
<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<!--<p id="notice">%= notice %></p>-->

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>